branches:
    only:
        - master
        - next-major
        - next-minor
        - next-patch
        - tmp

env:
    global:
      - languages=python,shell
      - BYEXAMPLE_CACHE_DISABLED=0

install: make deps
script: make travis-test

matrix:
    include:
        - name: "Github pages"
          language: ruby
          rvm:
            - 2.1
          install: "echo ok"
          script:
            - 'echo -e ''source "https://rubygems.org"\ngem "github-pages"'' > Gemfile'
            - "bundle install && cd docs && bundle exec jekyll build"
        - language: python
          python: "2.7"
          addons:
              apt_packages:
                  - pandoc
        - language: python
          python: "3.4"
          addons:
              apt_packages:
                  - pandoc

#- "3.4"
#- "3.5"
#- "3.6"
# - "3.7" travis doesn't support this yet
